apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config
  namespace: bankapp
data:
  #spring.datasource.url: jdbc:mysql://mysql:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  spring.datasource.url: jdbc:mysql://mysql.bankapp.svc.cluster.local:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  spring.jpa.hibernate.ddl-auto: update
  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  spring.jpa.show-sql: "true"
